create table if not exists public.off_season_championship_entries (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('LEMANS24', 'INDY300')),
  season_id text not null,
  driver_id bigint references public.drivers(id) on delete cascade,
  team_id bigint references public.teams(id) on delete set null,
  qualifying_position integer check (qualifying_position is null or qualifying_position > 0),
  race_position integer check (race_position is null or race_position > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_type, season_id, driver_id)
);

alter table public.off_season_championship_entries
  add column if not exists event_type text,
  add column if not exists season_id text,
  add column if not exists driver_id bigint,
  add column if not exists team_id bigint,
  add column if not exists qualifying_position integer,
  add column if not exists race_position integer,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists off_season_championship_entries_event_season_idx
  on public.off_season_championship_entries (event_type, season_id);

create or replace function public.set_off_season_championship_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_off_season_championship_updated_at on public.off_season_championship_entries;
create trigger trg_off_season_championship_updated_at
before update on public.off_season_championship_entries
for each row
execute function public.set_off_season_championship_updated_at();

alter table public.off_season_championship_entries enable row level security;

drop policy if exists "Public can read off season championships" on public.off_season_championship_entries;
create policy "Public can read off season championships"
on public.off_season_championship_entries
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated can insert off season championships" on public.off_season_championship_entries;
create policy "Authenticated can insert off season championships"
on public.off_season_championship_entries
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated can update off season championships" on public.off_season_championship_entries;
create policy "Authenticated can update off season championships"
on public.off_season_championship_entries
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete off season championships" on public.off_season_championship_entries;
create policy "Authenticated can delete off season championships"
on public.off_season_championship_entries
for delete
to authenticated
using (true);

notify pgrst, 'reload schema';
