alter table public.race_predictions
add column if not exists user_id uuid references auth.users(id) on delete set null;

create index if not exists race_predictions_user_id_idx
on public.race_predictions(user_id);

create table if not exists public.player_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  pseudo text not null unique,
  discord_name text not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

alter table public.player_profiles enable row level security;

drop policy if exists "Players can read player profiles" on public.player_profiles;
create policy "Players can read player profiles"
on public.player_profiles
for select
to authenticated
using (true);

drop policy if exists "Players can create their profile" on public.player_profiles;
create policy "Players can create their profile"
on public.player_profiles
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Players can update their profile" on public.player_profiles;
create policy "Players can update their profile"
on public.player_profiles
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.guess_driver_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  pseudo text not null,
  discord_name text,
  category_id text not null,
  challenge_day date not null,
  driver_id bigint not null,
  attempts integer not null default 0,
  won boolean not null default true,
  created_at timestamptz not null default now(),
  unique(user_id, category_id, challenge_day)
);

create index if not exists guess_driver_results_user_category_day_idx
on public.guess_driver_results(user_id, category_id, challenge_day desc);

alter table public.guess_driver_results enable row level security;

drop policy if exists "Players can read guess driver results" on public.guess_driver_results;
create policy "Players can read guess driver results"
on public.guess_driver_results
for select
to authenticated
using (true);

drop policy if exists "Players can insert own guess driver results" on public.guess_driver_results;
create policy "Players can insert own guess driver results"
on public.guess_driver_results
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Players can update own guess driver results" on public.guess_driver_results;
create policy "Players can update own guess driver results"
on public.guess_driver_results
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
