create table if not exists public.player_accounts (
  id bigint generated by default as identity primary key,
  pseudo text not null unique,
  discord_name text not null,
  access_code text not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

alter table public.player_accounts enable row level security;

drop policy if exists "Public can create player accounts" on public.player_accounts;
create policy "Public can create player accounts"
on public.player_accounts
for insert
to anon, authenticated
with check (true);

drop policy if exists "Public can login player accounts" on public.player_accounts;
create policy "Public can login player accounts"
on public.player_accounts
for select
to anon, authenticated
using (true);

alter table public.race_predictions
add column if not exists user_id uuid references auth.users(id) on delete set null;

alter table public.race_predictions
add column if not exists player_id bigint references public.player_accounts(id) on delete set null;

create index if not exists race_predictions_player_id_idx
on public.race_predictions(player_id);

do $$
begin
  if not exists (
    select 1
    from public.race_predictions
    where player_id is not null
    group by player_id, race_id
    having count(*) > 1
  ) then
    create unique index if not exists race_predictions_one_player_per_race_idx
    on public.race_predictions(player_id, race_id)
    where player_id is not null;
  end if;
end $$;

drop policy if exists "Public can create race predictions" on public.race_predictions;
create policy "Public can create race predictions"
on public.race_predictions
for insert
to anon, authenticated
with check (true);

drop policy if exists "Authenticated users can delete race predictions" on public.race_predictions;
create policy "Authenticated users can delete race predictions"
on public.race_predictions
for delete
to authenticated
using (true);

create table if not exists public.guess_driver_results (
  id bigint generated by default as identity primary key,
  player_id bigint references public.player_accounts(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  pseudo text not null,
  discord_name text,
  category_id text not null,
  challenge_day date not null,
  driver_id bigint not null,
  attempts integer not null default 0,
  score integer not null default 1,
  won boolean not null default true,
  created_at timestamptz not null default now(),
  unique(player_id, category_id, challenge_day)
);

alter table public.guess_driver_results
add column if not exists player_id bigint references public.player_accounts(id) on delete cascade;

alter table public.guess_driver_results
add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.guess_driver_results
add column if not exists score integer not null default 1;

alter table public.guess_driver_results
alter column user_id drop not null;

update public.guess_driver_results
set score = greatest(1, 11 - greatest(1, coalesce(attempts, 1)))
where won is true and (score is null or score <= 1);

do $$
begin
  alter table public.guess_driver_results
  drop constraint if exists guess_driver_results_user_id_category_id_challenge_day_key;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'guess_driver_results_player_id_category_id_challenge_day_key'
  ) then
    alter table public.guess_driver_results
    add constraint guess_driver_results_player_id_category_id_challenge_day_key
    unique (player_id, category_id, challenge_day);
  end if;
end $$;

create index if not exists guess_driver_results_player_category_day_idx
on public.guess_driver_results(player_id, category_id, challenge_day desc);

alter table public.guess_driver_results enable row level security;

drop policy if exists "Public can read guess driver results" on public.guess_driver_results;
create policy "Public can read guess driver results"
on public.guess_driver_results
for select
to anon, authenticated
using (true);

drop policy if exists "Public can save guess driver results" on public.guess_driver_results;
create policy "Public can save guess driver results"
on public.guess_driver_results
for insert
to anon, authenticated
with check (true);

drop policy if exists "Public can update guess driver results" on public.guess_driver_results;
create policy "Public can update guess driver results"
on public.guess_driver_results
for update
to anon, authenticated
using (true)
with check (true);
