create table if not exists public.feedback_requests (
  id bigint generated by default as identity primary key,
  type text not null default 'Suggestion',
  title text not null,
  content text not null,
  status text not null default 'pending',
  player_id bigint references public.player_accounts(id) on delete set null,
  pseudo text,
  discord_name text,
  page_url text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by text
);

alter table public.feedback_requests
add column if not exists type text not null default 'Suggestion';

alter table public.feedback_requests
add column if not exists title text not null default '';

alter table public.feedback_requests
add column if not exists content text not null default '';

alter table public.feedback_requests
add column if not exists status text not null default 'pending';

alter table public.feedback_requests
add column if not exists player_id bigint references public.player_accounts(id) on delete set null;

alter table public.feedback_requests
add column if not exists pseudo text;

alter table public.feedback_requests
add column if not exists discord_name text;

alter table public.feedback_requests
add column if not exists page_url text;

alter table public.feedback_requests
add column if not exists resolved_at timestamptz;

alter table public.feedback_requests
add column if not exists resolved_by text;

create index if not exists feedback_requests_status_created_idx
on public.feedback_requests(status, created_at desc);

alter table public.feedback_requests enable row level security;

drop policy if exists "Public can create feedback requests" on public.feedback_requests;
create policy "Public can create feedback requests"
on public.feedback_requests
for insert
to anon, authenticated
with check (true);

drop policy if exists "Authenticated admins can read feedback requests" on public.feedback_requests;
create policy "Authenticated admins can read feedback requests"
on public.feedback_requests
for select
to authenticated
using (true);

drop policy if exists "Authenticated admins can update feedback requests" on public.feedback_requests;
create policy "Authenticated admins can update feedback requests"
on public.feedback_requests
for update
to authenticated
using (true)
with check (true);

notify pgrst, 'reload schema';
